package de.post.ident.internal_core.reporting

/*
 * Error codes to use with AutoIDs incomplete interface
 */
enum class AutoIdErrorCode(val id: String, val message: String? = null) {
    NONE("MP0101"),

    USER_HAS_CANCELLED("MP0202", "AutoID canceled by user"),
    TIMEOUT_USER("MP0203"),
    TIMEOUT_APP("MP0204"),

    RECORDINGS_NOT_COMPLETE("MP0305"),
    RECORDINGS_QUALITY_TOO_LOW("MP0306"),

    DOCUMENT_NOT_RECOGNIZED("MP0407"),
    DOCUMENT_NOT_SUPPORTED("MP0408"),
    DOCUMENT_DAMAGED("MP0409"),
    DOCUMENT_COVERED("MP0410"),
    DOCUMENT_EXPIRED("MP0411"),

    RECORDED_FILES_FAULTY("MP0613"),
    BACKEND_CANNOT_FINISH("MP0614"),
    INCOMPLETE_OTHER_TECHNICAL_REASON("MP0615"),

    INCOMPLETE_ALREADY_FINISHED("MP0716"),
    INCOMPLETE_OTHER_REASON("MP0717"),

    WS_CONNECTION_PROBLEM("MP0818"),

    RESULT_DATA_FIELDS_DOCUMENT_NOT_COMPLETE("MP0919"),
    RESULT_ADDRESS_NOT_COMPLETE("MP0920")
}