// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: command_short.proto

package de.deutschepost.pi.mlservices.protobuf;

/**
 * <pre>
 * Wrapper for commands sent from the client to the server
 * </pre>
 *
 * Protobuf type {@code websocket.CommandWrapper}
 */
public  final class CommandWrapper extends
    com.google.protobuf.GeneratedMessageLite<
        CommandWrapper, CommandWrapper.Builder> implements
    // @@protoc_insertion_point(message_implements:websocket.CommandWrapper)
    CommandWrapperOrBuilder {
  private CommandWrapper() {
  }
  public static final int MAJOR_VERSION_FIELD_NUMBER = 1;
  private int majorVersion_;
  /**
   * <pre>
   * should currently be "2", reserved for future use
   * </pre>
   *
   * <code>sfixed32 major_version = 1;</code>
   * @return The majorVersion.
   */
  @java.lang.Override
  public int getMajorVersion() {
    return majorVersion_;
  }
  /**
   * <pre>
   * should currently be "2", reserved for future use
   * </pre>
   *
   * <code>sfixed32 major_version = 1;</code>
   * @param value The majorVersion to set.
   */
  private void setMajorVersion(int value) {
    
    majorVersion_ = value;
  }
  /**
   * <pre>
   * should currently be "2", reserved for future use
   * </pre>
   *
   * <code>sfixed32 major_version = 1;</code>
   */
  private void clearMajorVersion() {
    
    majorVersion_ = 0;
  }

  public static final int MINOR_VERSION_FIELD_NUMBER = 2;
  private int minorVersion_;
  /**
   * <pre>
   * should be "0", reserved for future use
   * </pre>
   *
   * <code>sfixed32 minor_version = 2;</code>
   * @return The minorVersion.
   */
  @java.lang.Override
  public int getMinorVersion() {
    return minorVersion_;
  }
  /**
   * <pre>
   * should be "0", reserved for future use
   * </pre>
   *
   * <code>sfixed32 minor_version = 2;</code>
   * @param value The minorVersion to set.
   */
  private void setMinorVersion(int value) {
    
    minorVersion_ = value;
  }
  /**
   * <pre>
   * should be "0", reserved for future use
   * </pre>
   *
   * <code>sfixed32 minor_version = 2;</code>
   */
  private void clearMinorVersion() {
    
    minorVersion_ = 0;
  }

  public static final int COMMAND_FIELD_NUMBER = 3;
  private com.google.protobuf.Any command_;
  /**
   * <pre>
   * the actual command, resolved via reflection on the server side
   * </pre>
   *
   * <code>.google.protobuf.Any command = 3;</code>
   */
  @java.lang.Override
  public boolean hasCommand() {
    return command_ != null;
  }
  /**
   * <pre>
   * the actual command, resolved via reflection on the server side
   * </pre>
   *
   * <code>.google.protobuf.Any command = 3;</code>
   */
  @java.lang.Override
  public com.google.protobuf.Any getCommand() {
    return command_ == null ? com.google.protobuf.Any.getDefaultInstance() : command_;
  }
  /**
   * <pre>
   * the actual command, resolved via reflection on the server side
   * </pre>
   *
   * <code>.google.protobuf.Any command = 3;</code>
   */
  private void setCommand(com.google.protobuf.Any value) {
    value.getClass();
  command_ = value;
    
    }
  /**
   * <pre>
   * the actual command, resolved via reflection on the server side
   * </pre>
   *
   * <code>.google.protobuf.Any command = 3;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeCommand(com.google.protobuf.Any value) {
    value.getClass();
  if (command_ != null &&
        command_ != com.google.protobuf.Any.getDefaultInstance()) {
      command_ =
        com.google.protobuf.Any.newBuilder(command_).mergeFrom(value).buildPartial();
    } else {
      command_ = value;
    }
    
  }
  /**
   * <pre>
   * the actual command, resolved via reflection on the server side
   * </pre>
   *
   * <code>.google.protobuf.Any command = 3;</code>
   */
  private void clearCommand() {  command_ = null;
    
  }

  public static de.deutschepost.pi.mlservices.protobuf.CommandWrapper parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static de.deutschepost.pi.mlservices.protobuf.CommandWrapper parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static de.deutschepost.pi.mlservices.protobuf.CommandWrapper parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static de.deutschepost.pi.mlservices.protobuf.CommandWrapper parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static de.deutschepost.pi.mlservices.protobuf.CommandWrapper parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static de.deutschepost.pi.mlservices.protobuf.CommandWrapper parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static de.deutschepost.pi.mlservices.protobuf.CommandWrapper parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static de.deutschepost.pi.mlservices.protobuf.CommandWrapper parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static de.deutschepost.pi.mlservices.protobuf.CommandWrapper parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static de.deutschepost.pi.mlservices.protobuf.CommandWrapper parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static de.deutschepost.pi.mlservices.protobuf.CommandWrapper parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static de.deutschepost.pi.mlservices.protobuf.CommandWrapper parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(de.deutschepost.pi.mlservices.protobuf.CommandWrapper prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Wrapper for commands sent from the client to the server
   * </pre>
   *
   * Protobuf type {@code websocket.CommandWrapper}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        de.deutschepost.pi.mlservices.protobuf.CommandWrapper, Builder> implements
      // @@protoc_insertion_point(builder_implements:websocket.CommandWrapper)
      de.deutschepost.pi.mlservices.protobuf.CommandWrapperOrBuilder {
    // Construct using de.deutschepost.pi.mlservices.protobuf.CommandWrapper.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * should currently be "2", reserved for future use
     * </pre>
     *
     * <code>sfixed32 major_version = 1;</code>
     * @return The majorVersion.
     */
    @java.lang.Override
    public int getMajorVersion() {
      return instance.getMajorVersion();
    }
    /**
     * <pre>
     * should currently be "2", reserved for future use
     * </pre>
     *
     * <code>sfixed32 major_version = 1;</code>
     * @param value The majorVersion to set.
     * @return This builder for chaining.
     */
    public Builder setMajorVersion(int value) {
      copyOnWrite();
      instance.setMajorVersion(value);
      return this;
    }
    /**
     * <pre>
     * should currently be "2", reserved for future use
     * </pre>
     *
     * <code>sfixed32 major_version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMajorVersion() {
      copyOnWrite();
      instance.clearMajorVersion();
      return this;
    }

    /**
     * <pre>
     * should be "0", reserved for future use
     * </pre>
     *
     * <code>sfixed32 minor_version = 2;</code>
     * @return The minorVersion.
     */
    @java.lang.Override
    public int getMinorVersion() {
      return instance.getMinorVersion();
    }
    /**
     * <pre>
     * should be "0", reserved for future use
     * </pre>
     *
     * <code>sfixed32 minor_version = 2;</code>
     * @param value The minorVersion to set.
     * @return This builder for chaining.
     */
    public Builder setMinorVersion(int value) {
      copyOnWrite();
      instance.setMinorVersion(value);
      return this;
    }
    /**
     * <pre>
     * should be "0", reserved for future use
     * </pre>
     *
     * <code>sfixed32 minor_version = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMinorVersion() {
      copyOnWrite();
      instance.clearMinorVersion();
      return this;
    }

    /**
     * <pre>
     * the actual command, resolved via reflection on the server side
     * </pre>
     *
     * <code>.google.protobuf.Any command = 3;</code>
     */
    @java.lang.Override
    public boolean hasCommand() {
      return instance.hasCommand();
    }
    /**
     * <pre>
     * the actual command, resolved via reflection on the server side
     * </pre>
     *
     * <code>.google.protobuf.Any command = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.Any getCommand() {
      return instance.getCommand();
    }
    /**
     * <pre>
     * the actual command, resolved via reflection on the server side
     * </pre>
     *
     * <code>.google.protobuf.Any command = 3;</code>
     */
    public Builder setCommand(com.google.protobuf.Any value) {
      copyOnWrite();
      instance.setCommand(value);
      return this;
      }
    /**
     * <pre>
     * the actual command, resolved via reflection on the server side
     * </pre>
     *
     * <code>.google.protobuf.Any command = 3;</code>
     */
    public Builder setCommand(
        com.google.protobuf.Any.Builder builderForValue) {
      copyOnWrite();
      instance.setCommand(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * the actual command, resolved via reflection on the server side
     * </pre>
     *
     * <code>.google.protobuf.Any command = 3;</code>
     */
    public Builder mergeCommand(com.google.protobuf.Any value) {
      copyOnWrite();
      instance.mergeCommand(value);
      return this;
    }
    /**
     * <pre>
     * the actual command, resolved via reflection on the server side
     * </pre>
     *
     * <code>.google.protobuf.Any command = 3;</code>
     */
    public Builder clearCommand() {  copyOnWrite();
      instance.clearCommand();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:websocket.CommandWrapper)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new de.deutschepost.pi.mlservices.protobuf.CommandWrapper();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "majorVersion_",
            "minorVersion_",
            "command_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\r\u0002\r\u0003" +
              "\t";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<de.deutschepost.pi.mlservices.protobuf.CommandWrapper> parser = PARSER;
        if (parser == null) {
          synchronized (de.deutschepost.pi.mlservices.protobuf.CommandWrapper.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<de.deutschepost.pi.mlservices.protobuf.CommandWrapper>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:websocket.CommandWrapper)
  private static final de.deutschepost.pi.mlservices.protobuf.CommandWrapper DEFAULT_INSTANCE;
  static {
    CommandWrapper defaultInstance = new CommandWrapper();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      CommandWrapper.class, defaultInstance);
  }

  public static de.deutschepost.pi.mlservices.protobuf.CommandWrapper getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<CommandWrapper> PARSER;

  public static com.google.protobuf.Parser<CommandWrapper> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

