// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: command_short.proto

package de.deutschepost.pi.mlservices.protobuf;

public interface CommandResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:websocket.CommandResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * reserved for future use, currently always set to SUCCESS, failure causes the websocket to
   * be closed immediately
   * </pre>
   *
   * <code>.websocket.CommandResponse.Status status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <pre>
   * reserved for future use, currently always set to SUCCESS, failure causes the websocket to
   * be closed immediately
   * </pre>
   *
   * <code>.websocket.CommandResponse.Status status = 1;</code>
   * @return The status.
   */
  de.deutschepost.pi.mlservices.protobuf.CommandResponse.Status getStatus();

  /**
   * <pre>
   * reserved for future use, currently always empty
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * reserved for future use, currently always empty
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   * the actual response from the server, type to be resolved by reflection by the recipient
   * </pre>
   *
   * <code>.google.protobuf.Any data = 3;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <pre>
   * the actual response from the server, type to be resolved by reflection by the recipient
   * </pre>
   *
   * <code>.google.protobuf.Any data = 3;</code>
   * @return The data.
   */
  com.google.protobuf.Any getData();
}
