// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: command_short.proto

package de.deutschepost.pi.mlservices.protobuf;

/**
 * <pre>
 * Wrapper for replies sent by the server
 * </pre>
 *
 * Protobuf type {@code websocket.CommandResponse}
 */
public  final class CommandResponse extends
    com.google.protobuf.GeneratedMessageLite<
        CommandResponse, CommandResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:websocket.CommandResponse)
    CommandResponseOrBuilder {
  private CommandResponse() {
    message_ = "";
  }
  /**
   * Protobuf enum {@code websocket.CommandResponse.Status}
   */
  public enum Status
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>SUCCESS = 0;</code>
     */
    SUCCESS(0),
    /**
     * <code>FAILURE = 1;</code>
     */
    FAILURE(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>SUCCESS = 0;</code>
     */
    public static final int SUCCESS_VALUE = 0;
    /**
     * <code>FAILURE = 1;</code>
     */
    public static final int FAILURE_VALUE = 1;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Status valueOf(int value) {
      return forNumber(value);
    }

    public static Status forNumber(int value) {
      switch (value) {
        case 0: return SUCCESS;
        case 1: return FAILURE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Status>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Status> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Status>() {
            @java.lang.Override
            public Status findValueByNumber(int number) {
              return Status.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return StatusVerifier.INSTANCE;
    }

    private static final class StatusVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new StatusVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return Status.forNumber(number) != null;
            }
          };

    private final int value;

    private Status(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:websocket.CommandResponse.Status)
  }

  public static final int STATUS_FIELD_NUMBER = 1;
  private int status_;
  /**
   * <pre>
   * reserved for future use, currently always set to SUCCESS, failure causes the websocket to
   * be closed immediately
   * </pre>
   *
   * <code>.websocket.CommandResponse.Status status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override
  public int getStatusValue() {
    return status_;
  }
  /**
   * <pre>
   * reserved for future use, currently always set to SUCCESS, failure causes the websocket to
   * be closed immediately
   * </pre>
   *
   * <code>.websocket.CommandResponse.Status status = 1;</code>
   * @return The status.
   */
  @java.lang.Override
  public de.deutschepost.pi.mlservices.protobuf.CommandResponse.Status getStatus() {
    de.deutschepost.pi.mlservices.protobuf.CommandResponse.Status result = de.deutschepost.pi.mlservices.protobuf.CommandResponse.Status.forNumber(status_);
    return result == null ? de.deutschepost.pi.mlservices.protobuf.CommandResponse.Status.UNRECOGNIZED : result;
  }
  /**
   * <pre>
   * reserved for future use, currently always set to SUCCESS, failure causes the websocket to
   * be closed immediately
   * </pre>
   *
   * <code>.websocket.CommandResponse.Status status = 1;</code>
   * @param value The enum numeric value on the wire for status to set.
   */
  private void setStatusValue(int value) {
      status_ = value;
  }
  /**
   * <pre>
   * reserved for future use, currently always set to SUCCESS, failure causes the websocket to
   * be closed immediately
   * </pre>
   *
   * <code>.websocket.CommandResponse.Status status = 1;</code>
   * @param value The status to set.
   */
  private void setStatus(de.deutschepost.pi.mlservices.protobuf.CommandResponse.Status value) {
    status_ = value.getNumber();
    
  }
  /**
   * <pre>
   * reserved for future use, currently always set to SUCCESS, failure causes the websocket to
   * be closed immediately
   * </pre>
   *
   * <code>.websocket.CommandResponse.Status status = 1;</code>
   */
  private void clearStatus() {
    
    status_ = 0;
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  private java.lang.String message_;
  /**
   * <pre>
   * reserved for future use, currently always empty
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    return message_;
  }
  /**
   * <pre>
   * reserved for future use, currently always empty
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(message_);
  }
  /**
   * <pre>
   * reserved for future use, currently always empty
   * </pre>
   *
   * <code>string message = 2;</code>
   * @param value The message to set.
   */
  private void setMessage(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    message_ = value;
  }
  /**
   * <pre>
   * reserved for future use, currently always empty
   * </pre>
   *
   * <code>string message = 2;</code>
   */
  private void clearMessage() {
    
    message_ = getDefaultInstance().getMessage();
  }
  /**
   * <pre>
   * reserved for future use, currently always empty
   * </pre>
   *
   * <code>string message = 2;</code>
   * @param value The bytes for message to set.
   */
  private void setMessageBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    message_ = value.toStringUtf8();
    
  }

  public static final int DATA_FIELD_NUMBER = 3;
  private com.google.protobuf.Any data_;
  /**
   * <pre>
   * the actual response from the server, type to be resolved by reflection by the recipient
   * </pre>
   *
   * <code>.google.protobuf.Any data = 3;</code>
   */
  @java.lang.Override
  public boolean hasData() {
    return data_ != null;
  }
  /**
   * <pre>
   * the actual response from the server, type to be resolved by reflection by the recipient
   * </pre>
   *
   * <code>.google.protobuf.Any data = 3;</code>
   */
  @java.lang.Override
  public com.google.protobuf.Any getData() {
    return data_ == null ? com.google.protobuf.Any.getDefaultInstance() : data_;
  }
  /**
   * <pre>
   * the actual response from the server, type to be resolved by reflection by the recipient
   * </pre>
   *
   * <code>.google.protobuf.Any data = 3;</code>
   */
  private void setData(com.google.protobuf.Any value) {
    value.getClass();
  data_ = value;
    
    }
  /**
   * <pre>
   * the actual response from the server, type to be resolved by reflection by the recipient
   * </pre>
   *
   * <code>.google.protobuf.Any data = 3;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeData(com.google.protobuf.Any value) {
    value.getClass();
  if (data_ != null &&
        data_ != com.google.protobuf.Any.getDefaultInstance()) {
      data_ =
        com.google.protobuf.Any.newBuilder(data_).mergeFrom(value).buildPartial();
    } else {
      data_ = value;
    }
    
  }
  /**
   * <pre>
   * the actual response from the server, type to be resolved by reflection by the recipient
   * </pre>
   *
   * <code>.google.protobuf.Any data = 3;</code>
   */
  private void clearData() {  data_ = null;
    
  }

  public static de.deutschepost.pi.mlservices.protobuf.CommandResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static de.deutschepost.pi.mlservices.protobuf.CommandResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static de.deutschepost.pi.mlservices.protobuf.CommandResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static de.deutschepost.pi.mlservices.protobuf.CommandResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static de.deutschepost.pi.mlservices.protobuf.CommandResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static de.deutschepost.pi.mlservices.protobuf.CommandResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static de.deutschepost.pi.mlservices.protobuf.CommandResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static de.deutschepost.pi.mlservices.protobuf.CommandResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static de.deutschepost.pi.mlservices.protobuf.CommandResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static de.deutschepost.pi.mlservices.protobuf.CommandResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static de.deutschepost.pi.mlservices.protobuf.CommandResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static de.deutschepost.pi.mlservices.protobuf.CommandResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(de.deutschepost.pi.mlservices.protobuf.CommandResponse prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Wrapper for replies sent by the server
   * </pre>
   *
   * Protobuf type {@code websocket.CommandResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        de.deutschepost.pi.mlservices.protobuf.CommandResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:websocket.CommandResponse)
      de.deutschepost.pi.mlservices.protobuf.CommandResponseOrBuilder {
    // Construct using de.deutschepost.pi.mlservices.protobuf.CommandResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * reserved for future use, currently always set to SUCCESS, failure causes the websocket to
     * be closed immediately
     * </pre>
     *
     * <code>.websocket.CommandResponse.Status status = 1;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override
    public int getStatusValue() {
      return instance.getStatusValue();
    }
    /**
     * <pre>
     * reserved for future use, currently always set to SUCCESS, failure causes the websocket to
     * be closed immediately
     * </pre>
     *
     * <code>.websocket.CommandResponse.Status status = 1;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      copyOnWrite();
      instance.setStatusValue(value);
      return this;
    }
    /**
     * <pre>
     * reserved for future use, currently always set to SUCCESS, failure causes the websocket to
     * be closed immediately
     * </pre>
     *
     * <code>.websocket.CommandResponse.Status status = 1;</code>
     * @return The status.
     */
    @java.lang.Override
    public de.deutschepost.pi.mlservices.protobuf.CommandResponse.Status getStatus() {
      return instance.getStatus();
    }
    /**
     * <pre>
     * reserved for future use, currently always set to SUCCESS, failure causes the websocket to
     * be closed immediately
     * </pre>
     *
     * <code>.websocket.CommandResponse.Status status = 1;</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(de.deutschepost.pi.mlservices.protobuf.CommandResponse.Status value) {
      copyOnWrite();
      instance.setStatus(value);
      return this;
    }
    /**
     * <pre>
     * reserved for future use, currently always set to SUCCESS, failure causes the websocket to
     * be closed immediately
     * </pre>
     *
     * <code>.websocket.CommandResponse.Status status = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      copyOnWrite();
      instance.clearStatus();
      return this;
    }

    /**
     * <pre>
     * reserved for future use, currently always empty
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      return instance.getMessage();
    }
    /**
     * <pre>
     * reserved for future use, currently always empty
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      return instance.getMessageBytes();
    }
    /**
     * <pre>
     * reserved for future use, currently always empty
     * </pre>
     *
     * <code>string message = 2;</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      copyOnWrite();
      instance.setMessage(value);
      return this;
    }
    /**
     * <pre>
     * reserved for future use, currently always empty
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      copyOnWrite();
      instance.clearMessage();
      return this;
    }
    /**
     * <pre>
     * reserved for future use, currently always empty
     * </pre>
     *
     * <code>string message = 2;</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMessageBytes(value);
      return this;
    }

    /**
     * <pre>
     * the actual response from the server, type to be resolved by reflection by the recipient
     * </pre>
     *
     * <code>.google.protobuf.Any data = 3;</code>
     */
    @java.lang.Override
    public boolean hasData() {
      return instance.hasData();
    }
    /**
     * <pre>
     * the actual response from the server, type to be resolved by reflection by the recipient
     * </pre>
     *
     * <code>.google.protobuf.Any data = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.Any getData() {
      return instance.getData();
    }
    /**
     * <pre>
     * the actual response from the server, type to be resolved by reflection by the recipient
     * </pre>
     *
     * <code>.google.protobuf.Any data = 3;</code>
     */
    public Builder setData(com.google.protobuf.Any value) {
      copyOnWrite();
      instance.setData(value);
      return this;
      }
    /**
     * <pre>
     * the actual response from the server, type to be resolved by reflection by the recipient
     * </pre>
     *
     * <code>.google.protobuf.Any data = 3;</code>
     */
    public Builder setData(
        com.google.protobuf.Any.Builder builderForValue) {
      copyOnWrite();
      instance.setData(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * the actual response from the server, type to be resolved by reflection by the recipient
     * </pre>
     *
     * <code>.google.protobuf.Any data = 3;</code>
     */
    public Builder mergeData(com.google.protobuf.Any value) {
      copyOnWrite();
      instance.mergeData(value);
      return this;
    }
    /**
     * <pre>
     * the actual response from the server, type to be resolved by reflection by the recipient
     * </pre>
     *
     * <code>.google.protobuf.Any data = 3;</code>
     */
    public Builder clearData() {  copyOnWrite();
      instance.clearData();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:websocket.CommandResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new de.deutschepost.pi.mlservices.protobuf.CommandResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "status_",
            "message_",
            "data_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\f\u0002\u0208" +
              "\u0003\t";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<de.deutschepost.pi.mlservices.protobuf.CommandResponse> parser = PARSER;
        if (parser == null) {
          synchronized (de.deutschepost.pi.mlservices.protobuf.CommandResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<de.deutschepost.pi.mlservices.protobuf.CommandResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:websocket.CommandResponse)
  private static final de.deutschepost.pi.mlservices.protobuf.CommandResponse DEFAULT_INSTANCE;
  static {
    CommandResponse defaultInstance = new CommandResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      CommandResponse.class, defaultInstance);
  }

  public static de.deutschepost.pi.mlservices.protobuf.CommandResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<CommandResponse> PARSER;

  public static com.google.protobuf.Parser<CommandResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

