// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: release.proto

package de.deutschepost.pi.mlservices.protobuf;

public interface DvfAddImageCommandMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:websocket.DvfAddImageCommandMessage)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * raw bytes of the jpeg image
   * </pre>
   *
   * <code>bytes image = 1;</code>
   * @return The image.
   */
  com.google.protobuf.ByteString getImage();
}
