// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: release.proto

package de.deutschepost.pi.mlservices.protobuf;

public interface DvfSetReferenceCommandMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:websocket.DvfSetReferenceCommandMessage)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * id of the case of this ident
   * </pre>
   *
   * <code>string case_id = 1;</code>
   * @return The caseId.
   */
  String getCaseId();
  /**
   * <pre>
   * id of the case of this ident
   * </pre>
   *
   * <code>string case_id = 1;</code>
   * @return The bytes for caseId.
   */
  com.google.protobuf.ByteString
      getCaseIdBytes();

  /**
   * <pre>
   * id of the ident
   * </pre>
   *
   * <code>sfixed64 ident_id = 2;</code>
   * @return The identId.
   */
  long getIdentId();

  /**
   * <pre>
   * id of the attempt
   * </pre>
   *
   * <code>sfixed64 attempt_id = 3;</code>
   * @return The attemptId.
   */
  long getAttemptId();

  /**
   * <pre>
   * id of the media record to store the sequence under
   * </pre>
   *
   * <code>sfixed64 dvf_sequence_media_record_id = 4;</code>
   * @return The dvfSequenceMediaRecordId.
   */
  long getDvfSequenceMediaRecordId();

  /**
   * <pre>
   * Class code of the template to use, e.g. "DEU_I8_card_front".
   * This should be the code determined by the document check or if none was detected, the empty string.
   * </pre>
   *
   * <code>string doc_code_pdc = 5;</code>
   * @return The docCodePdc.
   */
  String getDocCodePdc();
  /**
   * <pre>
   * Class code of the template to use, e.g. "DEU_I8_card_front".
   * This should be the code determined by the document check or if none was detected, the empty string.
   * </pre>
   *
   * <code>string doc_code_pdc = 5;</code>
   * @return The bytes for docCodePdc.
   */
  com.google.protobuf.ByteString
      getDocCodePdcBytes();

  /**
   * <pre>
   * The raw bytes of a supported image type (jpg or png), must be smaller than the
   * overall image size limit
   * </pre>
   *
   * <code>optional bytes dvf_reference_image = 6;</code>
   * @return Whether the dvfReferenceImage field is set.
   */
  boolean hasDvfReferenceImage();
  /**
   * <pre>
   * The raw bytes of a supported image type (jpg or png), must be smaller than the
   * overall image size limit
   * </pre>
   *
   * <code>optional bytes dvf_reference_image = 6;</code>
   * @return The dvfReferenceImage.
   */
  com.google.protobuf.ByteString getDvfReferenceImage();

  /**
   * <pre>
   * The id for the media record to store the reference image under
   * </pre>
   *
   * <code>optional uint64 dvf_reference_image_media_record_id = 7;</code>
   * @return Whether the dvfReferenceImageMediaRecordId field is set.
   */
  boolean hasDvfReferenceImageMediaRecordId();
  /**
   * <pre>
   * The id for the media record to store the reference image under
   * </pre>
   *
   * <code>optional uint64 dvf_reference_image_media_record_id = 7;</code>
   * @return The dvfReferenceImageMediaRecordId.
   */
  long getDvfReferenceImageMediaRecordId();
}
