// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: release.proto

package de.deutschepost.pi.mlservices.protobuf;

public interface FvLcChallengeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:websocket.FvLcChallengeResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * Challenge for the user in the vertical (↑↓) direction
   * </pre>
   *
   * <code>.websocket.FvLcChallengeResponse.TiltChallenge tilt_challenge = 1;</code>
   * @return The enum numeric value on the wire for tiltChallenge.
   */
  int getTiltChallengeValue();
  /**
   * <pre>
   * Challenge for the user in the vertical (↑↓) direction
   * </pre>
   *
   * <code>.websocket.FvLcChallengeResponse.TiltChallenge tilt_challenge = 1;</code>
   * @return The tiltChallenge.
   */
  FvLcChallengeResponse.TiltChallenge getTiltChallenge();

  /**
   * <pre>
   * Challenge for the user in the horizontal (←→) direction
   * </pre>
   *
   * <code>.websocket.FvLcChallengeResponse.PanChallenge pan_challenge = 2;</code>
   * @return The enum numeric value on the wire for panChallenge.
   */
  int getPanChallengeValue();
  /**
   * <pre>
   * Challenge for the user in the horizontal (←→) direction
   * </pre>
   *
   * <code>.websocket.FvLcChallengeResponse.PanChallenge pan_challenge = 2;</code>
   * @return The panChallenge.
   */
  FvLcChallengeResponse.PanChallenge getPanChallenge();
}
