// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: release.proto

package de.deutschepost.pi.mlservices.protobuf;

public interface FvLcFinishedResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:websocket.FvLcFinishedResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * If the process is complete (true) or should be repeated (false).
   * This is reserved for future use, at the moment it is always set to true as the current
   * workflow does not allow for a repeated FVLC phase
   * </pre>
   *
   * <code>bool is_complete = 1;</code>
   * @return The isComplete.
   */
  boolean getIsComplete();
}
