// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: release.proto

package de.deutschepost.pi.mlservices.protobuf;

public interface FvLcSetReferenceCommandMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:websocket.FvLcSetReferenceCommandMessage)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * id of the case of this ident
   * </pre>
   *
   * <code>string case_id = 1;</code>
   * @return The caseId.
   */
  String getCaseId();
  /**
   * <pre>
   * id of the case of this ident
   * </pre>
   *
   * <code>string case_id = 1;</code>
   * @return The bytes for caseId.
   */
  com.google.protobuf.ByteString
      getCaseIdBytes();

  /**
   * <pre>
   * id of the ident
   * </pre>
   *
   * <code>sfixed64 ident_id = 2;</code>
   * @return The identId.
   */
  long getIdentId();

  /**
   * <pre>
   * id of the attempt
   * </pre>
   *
   * <code>sfixed64 attempt_id = 3;</code>
   * @return The attemptId.
   */
  long getAttemptId();

  /**
   * <pre>
   * The raw bytes of a supported image type (jpg or png), must be smaller than the
   * overall image size limit
   * </pre>
   *
   * <code>bytes reference_image = 4;</code>
   * @return The referenceImage.
   */
  com.google.protobuf.ByteString getReferenceImage();

  /**
   * <pre>
   * The id for the media record to store the reference image under
   * </pre>
   *
   * <code>int64 reference_image_media_record_id = 5;</code>
   * @return The referenceImageMediaRecordId.
   */
  long getReferenceImageMediaRecordId();

  /**
   * <pre>
   * The id for the media record to store the frame grabs / webRTC stream (later) under
   * </pre>
   *
   * <code>int64 sequence_media_record_id = 6;</code>
   * @return The sequenceMediaRecordId.
   */
  long getSequenceMediaRecordId();
}
