// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: release.proto

package de.deutschepost.pi.mlservices.protobuf;

/**
 * <pre>
 * The final result from the server: signals that the liveness check is done.
 * The client should close the Websocket connection after receiving this message.
 * </pre>
 *
 * Protobuf type {@code websocket.FvLcFinishedResponse}
 */
public  final class FvLcFinishedResponse extends
    com.google.protobuf.GeneratedMessageLite<
        FvLcFinishedResponse, FvLcFinishedResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:websocket.FvLcFinishedResponse)
    FvLcFinishedResponseOrBuilder {
  private FvLcFinishedResponse() {
  }
  public static final int IS_COMPLETE_FIELD_NUMBER = 1;
  private boolean isComplete_;
  /**
   * <pre>
   * If the process is complete (true) or should be repeated (false).
   * This is reserved for future use, at the moment it is always set to true as the current
   * workflow does not allow for a repeated FVLC phase
   * </pre>
   *
   * <code>bool is_complete = 1;</code>
   * @return The isComplete.
   */
  @Override
  public boolean getIsComplete() {
    return isComplete_;
  }
  /**
   * <pre>
   * If the process is complete (true) or should be repeated (false).
   * This is reserved for future use, at the moment it is always set to true as the current
   * workflow does not allow for a repeated FVLC phase
   * </pre>
   *
   * <code>bool is_complete = 1;</code>
   * @param value The isComplete to set.
   */
  private void setIsComplete(boolean value) {
    
    isComplete_ = value;
  }
  /**
   * <pre>
   * If the process is complete (true) or should be repeated (false).
   * This is reserved for future use, at the moment it is always set to true as the current
   * workflow does not allow for a repeated FVLC phase
   * </pre>
   *
   * <code>bool is_complete = 1;</code>
   */
  private void clearIsComplete() {
    
    isComplete_ = false;
  }

  public static FvLcFinishedResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static FvLcFinishedResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static FvLcFinishedResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static FvLcFinishedResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static FvLcFinishedResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static FvLcFinishedResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static FvLcFinishedResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static FvLcFinishedResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static FvLcFinishedResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static FvLcFinishedResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static FvLcFinishedResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static FvLcFinishedResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(FvLcFinishedResponse prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * The final result from the server: signals that the liveness check is done.
   * The client should close the Websocket connection after receiving this message.
   * </pre>
   *
   * Protobuf type {@code websocket.FvLcFinishedResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        FvLcFinishedResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:websocket.FvLcFinishedResponse)
      FvLcFinishedResponseOrBuilder {
    // Construct using de.deutschepost.pi.mlservices.protobuf.FvLcFinishedResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * If the process is complete (true) or should be repeated (false).
     * This is reserved for future use, at the moment it is always set to true as the current
     * workflow does not allow for a repeated FVLC phase
     * </pre>
     *
     * <code>bool is_complete = 1;</code>
     * @return The isComplete.
     */
    @Override
    public boolean getIsComplete() {
      return instance.getIsComplete();
    }
    /**
     * <pre>
     * If the process is complete (true) or should be repeated (false).
     * This is reserved for future use, at the moment it is always set to true as the current
     * workflow does not allow for a repeated FVLC phase
     * </pre>
     *
     * <code>bool is_complete = 1;</code>
     * @param value The isComplete to set.
     * @return This builder for chaining.
     */
    public Builder setIsComplete(boolean value) {
      copyOnWrite();
      instance.setIsComplete(value);
      return this;
    }
    /**
     * <pre>
     * If the process is complete (true) or should be repeated (false).
     * This is reserved for future use, at the moment it is always set to true as the current
     * workflow does not allow for a repeated FVLC phase
     * </pre>
     *
     * <code>bool is_complete = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsComplete() {
      copyOnWrite();
      instance.clearIsComplete();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:websocket.FvLcFinishedResponse)
  }
  @Override
  @SuppressWarnings({"unchecked", "fallthrough"})
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new FvLcFinishedResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          Object[] objects = new Object[] {
            "isComplete_",
          };
          String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0007";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<FvLcFinishedResponse> parser = PARSER;
        if (parser == null) {
          synchronized (FvLcFinishedResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<FvLcFinishedResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:websocket.FvLcFinishedResponse)
  private static final FvLcFinishedResponse DEFAULT_INSTANCE;
  static {
    FvLcFinishedResponse defaultInstance = new FvLcFinishedResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      FvLcFinishedResponse.class, defaultInstance);
  }

  public static FvLcFinishedResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<FvLcFinishedResponse> PARSER;

  public static com.google.protobuf.Parser<FvLcFinishedResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

