// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: release.proto

package de.deutschepost.pi.mlservices.protobuf;

public interface UnknownCommandMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:websocket.UnknownCommandMessage)
    com.google.protobuf.MessageLiteOrBuilder {
}
