// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: command_short.proto

package de.deutschepost.pi.mlservices.protobuf;

public final class Ws {
  private Ws() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
